 bot.py                                                         import asyncio                                                  import json                                                     import logging                                                  from pathlib import Path                                        import discord                                                  from discord.ext import commands, tasks                         from discord import app_commands                                from TikTokApi import TikTokApi                                                                                                 # ---------- config ----------                                  CONFIG_PATH = Path("config.json")                               LAST_VIDEOS_PATH = Path("last_videos.json")                                                                                     with open(CONFIG_PATH, encoding="utf-8") as f:                      config = json.load(f)                                       
TOKEN = config["token"]                                         CHANNEL_ID = config["channel_id"]                               PING_ROLE_ID = config["ping_role_id"]                           USERNAMES = config["tiktok_usernames"]                          CHECK_INTERVAL = config["check_interval_minutes"]               # Laad het handmatige Chromium-pad in vanuit config.json
BROWSER_PATH = config.get("browser_executable_path", "/usr/bin/chromium-browser")                                               
# ---------- logging ----------                                 logging.basicConfig(level=logging.INFO)                         logger = logging.getLogger("tiktok_bot")
                                                                # ---------- storage ----------                                 def load_last_videos() -> dict[str, str]:                           if LAST_VIDEOS_PATH.exists():                                       with open(LAST_VIDEOS_PATH, encoding="utf-8") as f:                 return json.load(f)                                     return {}                                                                                                                   def save_last_videos(data: dict[str, str]) -> None:                 with open(LAST_VIDEOS_PATH, "w", encoding="utf-8") as f:            json.dump(data, f, indent=2)                                                                                            # ---------- bot ----------                                     intents = discord.Intents.default()                             bot = commands.Bot(command_prefix="!", intents=intents)                                                                         @bot.event                                                      async def on_ready():                                               logger.info(f"Logged in as {bot.user} (ID: {bot.user.id})")     # Sync slash commands                                           try:                                                                synced = await bot.tree.sync()                                  logger.info(f"Synced {len(synced)} slash command(s)")       except Exception as e:                                              logger.error(f"Failed to sync slash commands: {e}")                                                                         if not check_tiktok.is_running():                                   check_tiktok.start()                                                                                                    # ---------- Helper Functions ----------                        async def fetch_latest_video(username: str):                        """Fetch the latest video from a TikTok user"""                 try:
        # We maken een dummy ms_token aan die TikTok verplicht vereist
        ms_tokens = ["msToken_termux_compatibility_token_12345"]                                                                        async with TikTokApi() as api:                                      # GEWIJZIGD: Maak expliciet de sessie aan met de Chromium-browser uit je config                                                 await api.create_sessions(                                          ms_tokens=ms_tokens,                                            num_sessions=1,                                                 headless=True,                                                  executable_path=BROWSER_PATH                                )                                                                                                                               user = api.user(username)                                       videos = [v async for v in user.videos(count=1)]                if videos:                                                          return videos[0]                                            return None                                             except Exception as e:                                              logger.error(f"Error fetching video for @{username}: {e}")                                                                      return None                                                                                                             async def send_test_notification(channel, username, video):         """Send a test notification (same format as real one, but with TEST label)"""                                                   embed = discord.Embed(
        title=f"🧪 TEST: New TikTok from @{username}!",                 url=f"https://www.tiktok.com/@{username}/video/{video.id}",                                                                     description=f"[TEST MODE] {video.desc[:200] if video.desc else '*No description*'}",                                            color=0xffaa00,  # Orange color for test mode
    )
    embed.set_author(name=f"@{username}")
    embed.set_footer(text="🧪 TEST NOTIFICATION - No video was actually posted")

    if video.as_dict.get("video", {}).get("cover"):                     cover_url = video.as_dict["video"]["cover"]                     embed.set_image(url=cover_url)

    await channel.send(embed=embed)
                                                                # ---------- Real Check Task ----------
@tasks.loop(minutes=CHECK_INTERVAL)                             async def check_tiktok():
    """Automated task to check for new videos"""                    logger.info("Checking TikTok accounts for new videos...")       channel = bot.get_channel(CHANNEL_ID)
    if not channel:                                                     logger.error(f"Could not find Discord channel with ID {CHANNEL_ID}")                                                            return

    last_videos = load_last_videos()                                                                                                for username in USERNAMES:                                          video = await fetch_latest_video(username)                      if not video:                                                       continue                                            
        old_video_id = last_videos.get(username)                        if old_video_id != video.id:                                        # New video found!
            last_videos[username] = video.id
            save_last_videos(last_videos)                                                                                                   # Send real notification
            embed = discord.Embed(                                              title=f"📸 New TikTok from @{username}!",                       url=f"https://www.tiktok.com/@{username}/video/{video.id}",
                description=f"{video.desc[:200] if video.desc else '*No description*'}",
                color=0x00ffaa,                                             )
            embed.set_author(name=f"@{username}")                           if video.as_dict.get("video", {}).get("cover"):                     embed.set_image(url=video.as_dict["video"]["cover"])                                                                                                                                        await channel.send(content=f"<@&{PING_ROLE_ID}>", embed=embed)                                                                  logger.info(f"Notification sent for new video {video.id} from @{username}")                                                 await asyncio.sleep(2)                                                                                                  # ---------- Slash Commands ----------
@bot.tree.command(name="ping", description="Check if the bot is responsive")                                                    async def slash_ping(interaction: discord.Interaction):
    """Simple ping command to test the bot"""                       await interaction.response.send_message(f"Pong! 🏓 Latency: {round(bot.latency * 1000)}ms")
                                                                @bot.tree.command(name="test", description="Test the bot with any TikTok account")                                              @app_commands.describe(                                             username="TikTok username to test (without @)",                 ping_role="Whether to ping the role in test mode"
)                                                               async def slash_test(interaction: discord.Interaction, username: str, ping_role: bool = False):
    """Manually test the bot by fetching and displaying a TikTok video"""                                                           username = username.lower().strip()
    await interaction.response.defer()                                                                                              # Fetch the latest video                                        video = await fetch_latest_video(username)                      if not video:
        await interaction.followup.send(f"❌ Could not fetch video from `@{username}`. Make sure the account exists and has videos.", ephemeral=True)                                                   return                                                                                                                      # Send test notification                                        channel = interaction.channel                                   if ping_role:                                                       await channel.send(f"<@&{PING_ROLE_ID}>")                   await send_test_notification(channel, username, video)                                                                          await interaction.followup.send(f"✅ Test notification sent for `@{username}`! Video ID: `{video.id}`", ephemeral=True)                                                                     @bot.tree.command(name="test_all", description="Test all monitored accounts at once")                                           async def slash_test_all(interaction: discord.Interaction):         """Test all currently monitored accounts"""                     if not USERNAMES:                                                   await interaction.response.send_message("❌ No accounts are currently being monitored.", ephemeral=True)                        return                                                                                                                      await interaction.response.send_message(f"🧪 Testing {len(USERNAMES)} account(s)...", ephemeral=True)                           channel = interaction.channel                                   success_count = 0
                                                                    for username in USERNAMES:                                          video = await fetch_latest_video(username)                      if video:                                                           await send_test_notification(channel, username, video)                                                                          success_count += 1                                          await asyncio.sleep(1)                                                                                                      await interaction.followup.send(f"✅ Test complete! Sent {success_count}/{len(USERNAMES)} test notifications.", ephemeral=True)                                                                                                                             # ---------- Run ----------                                     if __name__ == "__main__":                                          bot.run(TOKEN)                                              
